### ISSUE TITLE
Nonexistent class is mapped in 1.16.2 and 1.16.3

### ISSUE THREAD

**Issue by i509VCB** [MinecraftForge/MCPConfig#125]
I've noticed that in 1.16.2 and 1.16.3 (I haven't tested other versions yet) that there is a class mapping that does not exist in the game any more. The specific mapping is `afd` -> `LowerStringMap`. The 1.16.3 client jar does not contain an `afd.class`.

**Comment by alcatrazEscapee** [comment]
Funnily enough, I had asked the same question in the forge discord a while back. Here was the response:

![reasons](https://user-images.githubusercontent.com/35673674/95616848-802fe180-0a38-11eb-9aaa-a719436d4b54.JPG)

So I would assume there's no issue here and that it's inclusion is intentional. 🤷
