### ISSUE TITLE
The "rename" step needs to support passing in an AccessTransformer file(s) to the SpecialSource

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/MCPConfig#21]
AccessTransformers need to be injected into SpecialSource to allow the generation of valid accesstransformed source code. Currently it seems this is not supported. I would assume it's intended to pass them into the rename step, where specialsource is called.

**Comment by LexManos** [comment]
The plan is to find somehow to do a final custom pre-decompile step that will let custom transformers run. 
I'm more inclined to turn https://github.com/MinecraftForge/AccessTransformers/blob/master/build.gradle into a executable jar, so that the same code thats packaged in Forge is run at dev time.
So we don't get anymore 'But it works in SpecialSource' issues.

But still haven't figured out how I am going to allow this yet. It won't be in MCPConfig it'll be in FG.

**Comment by LexManos** [comment]
https://github.com/LexManos/ForgeGradle/commit/26efb1353f56c833f626cc35c5890ebad90185c7
